{{- if .Values.ethMock.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plinko-pir.fullname" . }}-eth-mock
  labels:
    {{- include "plinko-pir.componentLabels" (dict "component" "eth-mock" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.ethMock.replicaCount }}
  strategy:
    type: Recreate  # Can't have multiple Anvil instances with same state
  selector:
    matchLabels:
      {{- include "plinko-pir.componentSelectorLabels" (dict "component" "eth-mock" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "plinko-pir.componentSelectorLabels" (dict "component" "eth-mock" "root" .) | nindent 8 }}
    spec:
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.ethMock.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.ethMock.nodeSelector | nindent 8 }}
      {{- else if .Values.global.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.global.nodeSelector | nindent 8 }}
      {{- end }}
      containers:
      - name: eth-mock
        image: "{{ .Values.ethMock.image.repository }}:{{ .Values.ethMock.image.tag }}"
        imagePullPolicy: {{ .Values.ethMock.image.pullPolicy }}
        command:
          - anvil
          - --accounts
          - "{{ .Values.ethMock.config.accounts | int }}"
          - --balance
          - "{{ .Values.ethMock.config.balance }}"
          - --block-time
          - "{{ .Values.ethMock.config.blockTime | int }}"
          - --host
          - "0.0.0.0"
          - --port
          - "8545"
        ports:
        - name: rpc
          containerPort: 8545
          protocol: TCP
        resources:
          {{- toYaml .Values.ethMock.resources | nindent 10 }}
        {{- if .Values.ethMock.livenessProbe.enabled }}
        livenessProbe:
          {{- toYaml .Values.ethMock.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.ethMock.readinessProbe.enabled }}
        readinessProbe:
          {{- toYaml .Values.ethMock.readinessProbe | nindent 10 }}
        {{- end }}
{{- end }}
